version: '3.8'

networks:
  polly:
    name: polly-network

services:
  prometheus:
    build:
      context: ./scripts/prometheus
    container_name:  prometheus-metric-service 
    ports:
      - 9090:9090
    networks:
      - polly

  grafana:
    build:
      context: ./scripts/grafana
    container_name: grafana-monitoring-service  
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - polly
  
  otel-collector:
    image: otel/opentelemetry-collector:0.73.0
    container_name: otel-collector-service
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./scripts/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
    networks:
      - polly